name: demo
channels:
- conda-forge
dependencies:
  - papermill
  - ipykernel
  - ipytree
  - python =3.13
  - bagofholding =0.1.11
  - flowrep =0.5.1
  - python-workflow-definition =0.1.5
  - semantikon =1.3.1